spring.application.name=smart-campus-navigation
spring.datasource.url=jdbc:sqlite:database/campus.db
spring.datasource.driver-class-name=org.sqlite.JDBC
server.port=8080
server.error.include-message=always
logging.level.org.springframework.jdbc.core=INFO
